// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { brokeredPreviewStorage } from './previewAuthStorage';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

const isSupabaseConfigured = Boolean(
  SUPABASE_URL &&
  typeof SUPABASE_URL === 'string' &&
  SUPABASE_URL.startsWith('http') &&
  SUPABASE_PUBLISHABLE_KEY &&
  typeof SUPABASE_PUBLISHABLE_KEY === 'string' &&
  SUPABASE_PUBLISHABLE_KEY.length > 5
);

function createMockSupabaseClient() {
  const listeners = new Set<(event: string, session: any) => void>();

  const getStoredUser = () => {
    try {
      const stored = localStorage.getItem('qalami_mock_user');
      if (stored) return JSON.parse(stored);
    } catch {
      // ignore
    }
    const defaultUser = {
      id: 'demo-user-qalami',
      email: 'user@qalami.ai',
      user_metadata: { full_name: 'مستخدم قلمي' },
      app_metadata: {},
      created_at: new Date().toISOString(),
    };
    try {
      localStorage.setItem('qalami_mock_user', JSON.stringify(defaultUser));
    } catch {
      // ignore
    }
    return defaultUser;
  };

  const notifyAuthChange = (event: string, session: any) => {
    listeners.forEach((cb) => {
      try {
        cb(event, session);
      } catch (err) {
        console.error(err);
      }
    });
  };

  const getStoredCredits = () => {
    const user = getStoredUser();
    const key = `qalami_user_credits_${user?.id || 'demo'}`;
    try {
      const stored = localStorage.getItem(key);
      if (stored) return JSON.parse(stored);
    } catch {
      // ignore
    }
    const initialCredits = {
      user_id: user?.id || 'demo',
      balance: 15,
      plan: 'free',
      monthly_grant: 0,
      renews_at: null,
    };
    try {
      localStorage.setItem(key, JSON.stringify(initialCredits));
    } catch {
      // ignore
    }
    return initialCredits;
  };

  const saveCredits = (credits: any) => {
    const user = getStoredUser();
    const key = `qalami_user_credits_${user?.id || 'demo'}`;
    try {
      localStorage.setItem(key, JSON.stringify(credits));
    } catch {
      // ignore
    }
  };

  const getStoredPosts = (): any[] => {
    try {
      const stored = localStorage.getItem('qalami_saved_posts');
      if (stored) return JSON.parse(stored);
    } catch {
      // ignore
    }
    return [];
  };

  const savePosts = (posts: any[]) => {
    try {
      localStorage.setItem('qalami_saved_posts', JSON.stringify(posts));
    } catch {
      // ignore
    }
  };

  return {
    auth: {
      async getSession() {
        const user = getStoredUser();
        if (!user) return { data: { session: null }, error: null };
        const session = {
          access_token: 'mock-access-token-qalami',
          refresh_token: 'mock-refresh-token-qalami',
          expires_in: 3600,
          expires_at: Math.floor(Date.now() / 1000) + 3600,
          user,
        };
        return { data: { session }, error: null };
      },
      async getUser() {
        const user = getStoredUser();
        return { data: { user }, error: null };
      },
      onAuthStateChange(callback: (event: string, session: any) => void) {
        listeners.add(callback);
        return {
          data: {
            subscription: {
              unsubscribe: () => {
                listeners.delete(callback);
              },
            },
          },
        };
      },
      async signUp({ email, password, options }: any) {
        const user = {
          id: `user-${Date.now()}`,
          email,
          user_metadata: { full_name: options?.data?.full_name || email.split('@')[0] },
          app_metadata: {},
          created_at: new Date().toISOString(),
        };
        try {
          localStorage.setItem('qalami_mock_user', JSON.stringify(user));
        } catch {
          // ignore
        }
        const session = {
          access_token: 'mock-access-token-qalami',
          refresh_token: 'mock-refresh-token-qalami',
          expires_in: 3600,
          expires_at: Math.floor(Date.now() / 1000) + 3600,
          user,
        };
        notifyAuthChange('SIGNED_IN', session);
        return { data: { user, session }, error: null };
      },
      async signInWithPassword({ email }: any) {
        const user = {
          id: `user-${Date.now()}`,
          email,
          user_metadata: { full_name: email.split('@')[0] },
          app_metadata: {},
          created_at: new Date().toISOString(),
        };
        try {
          localStorage.setItem('qalami_mock_user', JSON.stringify(user));
        } catch {
          // ignore
        }
        const session = {
          access_token: 'mock-access-token-qalami',
          refresh_token: 'mock-refresh-token-qalami',
          expires_in: 3600,
          expires_at: Math.floor(Date.now() / 1000) + 3600,
          user,
        };
        notifyAuthChange('SIGNED_IN', session);
        return { data: { user, session }, error: null };
      },
      async signInWithOAuth({ provider }: any) {
        const user = {
          id: `oauth-user-${Date.now()}`,
          email: `google.user@qalami.ai`,
          user_metadata: { full_name: 'مستخدم جوجل' },
          app_metadata: { provider },
          created_at: new Date().toISOString(),
        };
        try {
          localStorage.setItem('qalami_mock_user', JSON.stringify(user));
        } catch {
          // ignore
        }
        const session = {
          access_token: 'mock-access-token-qalami',
          refresh_token: 'mock-refresh-token-qalami',
          expires_in: 3600,
          expires_at: Math.floor(Date.now() / 1000) + 3600,
          user,
        };
        notifyAuthChange('SIGNED_IN', session);
        return { data: { user, session }, error: null };
      },
      async signOut() {
        try {
          localStorage.removeItem('qalami_mock_user');
        } catch {
          // ignore
        }
        notifyAuthChange('SIGNED_OUT', null);
        return { error: null };
      },
    },
    from(table: string) {
      let filters: Array<{ col: string; val: any }> = [];
      let isSingle = false;
      let isMaybeSingle = false;
      let limitCount: number | null = null;
      let isDelete = false;
      let insertData: any = null;

      const execute = async () => {
        if (table === 'user_credits') {
          const credits = getStoredCredits();
          if (isSingle || isMaybeSingle) {
            return { data: credits, error: null };
          }
          return { data: [credits], error: null };
        }

        if (table === 'user_roles') {
          const adminRole = { role: 'admin' };
          if (isSingle || isMaybeSingle) {
            return { data: adminRole, error: null };
          }
          return { data: [adminRole], error: null };
        }

        if (table === 'saved_posts') {
          let posts = getStoredPosts();
          if (isDelete) {
            for (const f of filters) {
              posts = posts.filter((p) => p[f.col] !== f.val);
            }
            savePosts(posts);
            return { data: null, error: null };
          }
          if (insertData) {
            const newRecord = {
              id: `post-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`,
              created_at: new Date().toISOString(),
              ...(Array.isArray(insertData) ? insertData[0] : insertData),
            };
            posts.unshift(newRecord);
            savePosts(posts);
            return { data: isSingle ? newRecord : [newRecord], error: null };
          }
          // Query
          let result = [...posts];
          for (const f of filters) {
            result = result.filter((p) => p[f.col] === f.val);
          }
          if (limitCount) {
            result = result.slice(0, limitCount);
          }
          if (isSingle || isMaybeSingle) {
            return { data: result[0] || null, error: null };
          }
          return { data: result, error: null };
        }

        return { data: isSingle || isMaybeSingle ? null : [], error: null };
      };

      const builder: any = {
        select: (_cols?: string) => builder,
        insert: (data: any) => {
          insertData = data;
          return builder;
        },
        delete: () => {
          isDelete = true;
          return builder;
        },
        eq: (col: string, val: any) => {
          filters.push({ col, val });
          return builder;
        },
        order: (_col: string, _opts?: any) => builder,
        limit: (count: number) => {
          limitCount = count;
          return builder;
        },
        single: () => {
          isSingle = true;
          return builder;
        },
        maybeSingle: () => {
          isMaybeSingle = true;
          return builder;
        },
        then: (onfulfilled?: (val: any) => any, onrejected?: (err: any) => any) => {
          return execute().then(onfulfilled, onrejected);
        },
      };

      return builder;
    },
    async rpc(funcName: string, args?: any) {
      if (funcName === 'renew_credits') {
        return { data: null, error: null };
      }
      if (funcName === 'consume_credits') {
        const credits = getStoredCredits();
        const amt = args?._amount ?? 1;
        if (credits.balance < amt && credits.plan !== 'pro') {
          return { data: null, error: { message: 'NO_CREDITS' } };
        }
        credits.balance = Math.max(0, credits.balance - amt);
        saveCredits(credits);
        return { data: credits.balance, error: null };
      }
      if (funcName === 'refund_credits') {
        const credits = getStoredCredits();
        const amt = args?._amount ?? 1;
        credits.balance += amt;
        saveCredits(credits);
        return { data: credits.balance, error: null };
      }
      return { data: null, error: null };
    },
  };
}

export const supabase: any = isSupabaseConfigured
  ? createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      global: {
        fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
      },
      auth: {
        storage: brokeredPreviewStorage(),
        persistSession: true,
        autoRefreshToken: true,
      },
    })
  : createMockSupabaseClient();
